# Generated by Django 3.1.11 on 2021-06-09 04:20

from django.db import migrations, models
import testuuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', testuuid.models.UniqueIdentifierField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'testing',
            },
        ),
    ]
