# Generated by Django 3.1.11 on 2021-06-08 16:49

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testuuid', '0002_auto_20210608_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='money',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='USD', max_digits=11),
        ),
    ]
