# Generated by Django 3.1.11 on 2021-06-08 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testuuid', '0003_auto_20210608_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='money',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='money_currency',
        ),
        migrations.AddField(
            model_name='testing',
            name='id2',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
