# Generated by Django 3.1.11 on 2021-06-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adver',
            table='adveris',
        ),
    ]
