# Generated by Django 3.1.11 on 2021-06-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advers', '0004_auto_20210607_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='adver',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advers', to='advers.owner', verbose_name='Владелец'),
        ),
    ]
