# Generated by Django 3.1.11 on 2021-06-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adevertisement',
            new_name='Advertisement',
        ),
    ]
