# Generated by Django 3.1.11 on 2021-06-07 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20210607_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='crt_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(default=0, verbose_name='цена продукта'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='view_cnt',
            field=models.IntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
    ]
